### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by leader22** [nodefest/nodefest.github.com#19]
やること貯まってきた！

- [x] http://nodejs.connpass.com/event/20741/ へのリンクつなげる
- [x] スポンサー更新
  - [x] 株式会社ドワンゴ
  - [x] 株式会社リクルートテクノロジーズ
  - [x] ニフティ株式会社
  - [x] ユニバ株式会社
  - [x] 株式会社パエリア
  - [x] サイバーエージェント
  - [x] Kaizen Platform, Inc.
  - [x] ピクセルグリッド
  - [x] グリー株式会社
  - [x] 株式会社ディー・エヌ・エー

**Comment by leader22** [comment]
done!
